version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db  # checking if db is needed or not.
    restart: always
